apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-dp
spec:
  selector:
    matchLabels:
      type: back-end
  replicas: 1
  template:
    metadata:
      labels:
        type: back-end
    spec:
      containers:
      - image: shrivardhanreddy/servertest
        name: server