apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: NodePort
  selector:
    type: back-end
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30025